package:
  name: cbmpy
  version: "0.7.18"

source:
  svn_url: https://svn.code.sf.net/p/cbmpy/code/trunk/cbmpy
  svn_rev: 628

build:
  number: 2
  include_recipe: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - sympy
    - python-libsbml
    - scipy
    - matplotlib
    - biopython
    - suds
    - nose
    
    
about:
  home: http://cbmpy.sourceforge.net
  license: GPL
  licence_file: LICENCE_GPLv3.txt
  summary: Constraint-based modelling in Python

extra:
  maintainers:
   - Brett G. Olivier
