package:
  name: cbmpy
  version: "0.7.7"

source:
  url: https://pypi.python.org/packages/a8/16/bafddbe7124bd7ee4c94ee8160a27ddc07367924f0e57b8a283518e7fa1c/cbmpy-0.7.7.tar.gz
  md5: db17d25b89777238a3f9e584f3064436

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - sympy
    - python-libsbml
    - scipy
    - matplotlib
    - biopython
    - suds
    
about:
  home: http://cbmpy.sourceforge.net
  license: GPL
  licence_file: LICENCE_GPLv3.txt
