package:
  name: cbmpy
  version: "0.7.21"

source:
  svn_url: https://svn.code.sf.net/p/cbmpy/code/trunk/cbmpy
  svn_rev: 648
  
build:
  number: 1
  include_recipe: False

requirements:
  build:
    - python=2.7
    - setuptools
  run:
    - python
    - numpy
    - sympy
    - python-libsbml
#    - scipy>=1.0.0
    - matplotlib
    - nose
    - biopython
    - xlrd
    - xlwt
    
about:
  home: http://cbmpy.sourceforge.net
  license: GPL
  licence_file: LICENCE_GPLv3.txt
  summary: Constraint-based modelling in Python

extra:
  maintainers:
   - Brett G. Olivier
