package:
  name: cbmpy
  version: "0.7.19"

source:
  svn_url: https://svn.code.sf.net/p/cbmpy/code/trunk/cbmpy
  svn_rev: 633

build:
  number: 2
  include_recipe: False

requirements:
  build:
    - python=2.7
    - setuptools
  run:
    - python=2.7
    - numpy
    - sympy
    - python-libsbml
    - scipy>=1.0.0
    - matplotlib
    - nose
#    - biopython
    
about:
  home: http://cbmpy.sourceforge.net
  license: GPL
  licence_file: LICENCE_GPLv3.txt
  summary: Constraint-based modelling in Python

extra:
  maintainers:
   - Brett G. Olivier
