package:
  name: cbmpy
  version: "0.8.0"

source:
    git_url: https://github.com/SystemsBioinformatics/cbmpy.git
#    git_rev: 0.8.0
    git_depth: 1 # (Defaults to -1/not shallow)
  
build:
  number: 1
  include_recipe: True

requirements:
  build:
    - python=3.6
    - setuptools
  run:
    - python>=3.6
    - numpy
    - sympy
    - python-libsbml
    - nose
    - biopython
    - xlrd
    - xlwt
    
about:
  home: http://cbmpy.sourceforge.net
  license: GPL
  licence_file: LICENCE_GPLv3.txt
  summary: Constraint-based modelling in Python

extra:
  maintainers:
   - Brett G. Olivier
